pipeline {
    agent {
        docker {
            image 'maven:3.5.4'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'pwd;cd sjapp/jenkins ;mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'pwd;cd sjapp/jenkins ;mvn test'
            }
            post {
                always {
                    junit 'sjapp/jenkins/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
